### ISSUE TITLE
Yarn 2 support

### ISSUE THREAD

**Issue by alexander-sergeev** [GoogleCloudPlatform/artifact-registry-npm-tools#16]
Do you have plans to support [`.yarnrc.yml`](https://yarnpkg.com/configuration/yarnrc) files?

Yarn since version 2 [doesn't support](https://yarnpkg.com/getting-started/migration#dont-use-npmrc-files) `.npmrc` anymore, so you need to provide info in .yarnrc.yml:
```
npmScopes:
  workspace:
    npmRegistryServer: 'https://region-npm.pkg.dev/project/repo'
    npmAlwaysAuth: true
    npmAuthToken: 'abc'
```
Currently `google-artifactregistry-auth` doesn't support this.

**Comment by yihanzhen** [comment]
Hi @alexander-sergeev thanks for reporting this and providing the snippet of .yarnrc.yml. We are working on adding support for yarn but there's still a lot in the works. Please stay tuned.

FWIW if you are developing stuff in your own environment (i.e. not as a CI/CD pipeline) you can manually substitute the `npmAuthToken` part with tokens from `gcloud auth print-access-token` and it should allow you to push/pull.

**Comment by alexander-sergeev** [comment]
Hi,
Yeah, we solved it by providing fresh access token to yarn via environment variable.

**Comment by lberrocal** [comment]
This is a blocker for a current project and we haven't found an ideal solution
> Hi,
> Yeah, we solved it by providing fresh access token to yarn via environment variable.

Would you mind sharing some details on this?

**Comment by alexander-sergeev** [comment]
@lberrocal 
You can use env variables in your `.yarnrc.yml` (https://yarnpkg.com/configuration/yarnrc).
Write token to env before calling yarn. Notice that tokens are short-lived.
 `export NPM_TOKEN=$(gcloud auth print-access-token)`

**Comment by AndyClausen** [comment]
Does anyone have an easy way of doing this? I'd hate to require my colleagues to update their token every time they want to install or update private packages, and I can't figure how to do it 😕

**Comment by AndyClausen** [comment]
I figured out a way to do it nicely. I wrote a plugin for it:
https://github.com/AndyClausen/yarn-plugin-gcp-auth/
Enjoy 😄

**Comment by riaanduplessis** [comment]
Thought I'd share my experience with this as I've been intensively working on a private node package for our software at work and setting up all the areas that needs to be authenticated to install the package.

I had to deal with a few parts that needed to be authenticated and also to make it as simple as possible, mainly: 

- Publishing to Artifact Registry during a Cloud Build run.
- Installing from Artifact Registry locally when using the package.
- Installing from Artifact Registry within GitHub Action workflows.

The yarn plugin for some reason just didn't work at all for me, no matter where I used it and what way I was authenticated using the gcloud CLI.

## For publishing in Cloud Build

I resorted to using the normal `npm publish` command and simply kept a `.npmrc` file in my project's root directory with the registry details along with the `.yarnrc.yml` file. 

> This was because I couldn't make use of the token retrieved by `gcloud auth print-access-token` as it kept returning a `forbidden` response when setting it as the `npmAuthToken` in the `.yarnrc.yml` file. IAM roles are correctly added to the Cloud Build service account, so not sure why this happens.

So this config is solely used for publishing:

```npmrc
@<scope>:registry=https://<region>-npm.pkg.dev/<project>/<repository>/
//<region>-npm.pkg.dev/<project>/<repository>/:always-auth=true

```

I then added a prepublishOnly hook to my scripts in `package.json` that generates a token using the `google-artifactregistry-auth` package:

```json
"scripts": {
  "artifactregistry-login": "yarn dlx google-artifactregistry-auth",
  "prepublishOnly": "yarn artifactregistry-login"
}
```

This allows for a single step in the `cloudbuild.yaml` file:

```yaml
# ... dependencies / build / test here

# Publish new version to dist channel.
- name: node:lts-alpine
  entrypoint: npm
  args: [ publish, --tag, $_DIST_CHANNEL ]
```

## Local installations

Here the `gcloud auth print-access-token` token works, so applications making use of the package are simply encouraged to add the following as a script in their `package.json` and run it before they do installations.

```json
"scripts": {
   "set-registry-token": "yarn config set --home npmAuthToken $(gcloud auth print-access-token --project=<project>)"
}
```

And in their `.yarnrc.yml` files:

```yaml
npmScopes:
 <scope>:
    npmAlwaysAuth: true
    npmRegistryServer: "https://<region>-npm.pkg.dev/<project>/<repository>/"
```

## GitHub Action Workflow Installations (To be confirmed)

_Also after having set the registry details in the project's `.yarnrc.yml` file._

I'll come back and edit this once I've confirmed this as I'm in the process of testing it, but thus far I've set up Workload Identity Federation between GitHub and Google Cloud. 

My thinking is that the access token generated by the `google-github-actions/auth` action can then be used to authenticate to Artifact Registry, otherwise I'll probably look to add another step and make use of the `gcloud` action to generate a token.

This is the workflow steps (_still need to confirm if viable_):

```yaml
  # Configure Workload Identity Federation which will create an access token
  # to be used in the subsequent steps.
  - name: Authenticate to Google Cloud
    id: auth
    uses: 'google-github-actions/auth@v0'
    with:
      project_id: <project-id>
      token_format: access_token
      workload_identity_provider: projects/<project-number>/locations/global/workloadIdentityPools/<pool>/providers/<provider>
      service_account: <account>@<project>.iam.gserviceaccount.com

  # The registry is set in the project's `.yarnrc.yml` file so
  # here we only set the authorisation token created in the `auth` step through the
  # YARN_NPM_AUTH_TOKEN environment variable.
  - name: Install private package
    env:
      YARN_NPM_AUTH_TOKEN: ${{ steps.auth.outputs.access_token }}
```

**Comment by KubaJastrz** [comment]
This command works for me:

```
yarn config set --home npmAuthToken $(gcloud auth print-access-token)
```

I use it instead of 

```
npx google-artifactregistry-auth
```

**Comment by kiransmith** [comment]
Taking inspiration from the above answer - in the case of where you are using multiple npmScopes (as I am), then the below scales slightly better.

`yarn config set --home --json 'npmScopes.<scopeName>.npmAuthToken' "\"$(gcloud auth print-access-token)\""`

**Comment by mike-sirs** [comment]
that one works for me using github actions and no need to generate access-token

```
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        project_id: google-project
        workload_identity_provider: ${{ env.GCP_WIF_URL }}

    - name: Install dependencies
      run: |
        npm config set @hailtrace:registry=https://us-central1-npm.pkg.dev/google-project/npm-packages/
        npx google-artifactregistry-auth
        yarn install
```
