### ISSUE TITLE
npx google-artifactregistry-auth v3.1.1 succeeds but subsequent npm install hits 403 forbidden for private package

### ISSUE THREAD

**Issue by richjyoung** [GoogleCloudPlatform/artifact-registry-npm-tools#52]
**This does not happen with v3.1.0**

Running in GitLab CI on a private runner, executing the following (*** masked for privacy):

```yaml
before_script:
  - gcloud auth activate-service-account ***@***.iam.gserviceaccount.com --key-file=*** --project=***
  - npx --yes google-artifactregistry-auth
  - npm ci --production=false
script:
  - ./node_modules/.bin/vitest run --coverage
```

The output from GitLab CI Job is as follows:

```
$ npx --yes google-artifactregistry-auth
Retrieving application default credentials...
Success!
$ npm ci
npm WARN deprecated json-schema-ref-parser@9.0.9: Please switch to @apidevtools/json-schema-ref-parser
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://us-npm.pkg.dev/***/***/@***/***/-/@***-3.0.1.tgz - The caller does not have permission.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-28T08_28_36_481Z-debug-0.log
```

The referenced log file contains no further information than the above output.

Version 3.1.0 does not have this issue, if we run `npx --yes google-artifactregistry-auth@v3.1.0` (which we have had to commit to our .gitlab-ci.yml to fix our pipeline) then this works as expected. Please let me know if there is any further information I can provide, however I am unable to share a minimal example as this involves organisation private data.
