### ISSUE TITLE
auth to artifact registry broken when using workload identity

### ISSUE THREAD

**Issue by arcrank** [GoogleCloudPlatform/artifact-registry-npm-tools#64]
Spent hours trying to poke around in GitHub actions as I could not get step to work and then I saw some of closed issues that have occurred for the same reason in the past.  So I am wondering if current versions are broken due to a latent change

Following setups with newer versions in GitHub actions.
```
    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        create_credentials_file: true
        project_id: $project_id
        service_account: 'github@$project_id.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/$project_number/locations/global/workloadIdentityPools/githubactions/providers/github'
```

Will succeed and even steps for installing gcloud sdk etc succeed, but when we get to registry setup it fails

```
      run: npx google-artifactregistry-auth
```
 error:
```
Run npx google-artifactregistry-auth
  npx google-artifactregistry-auth
  shell: /usr/bin/bash -e {0}
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/webapp/webapp/gha-creds-71c882d7c34cc120.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/webapp/webapp/gha-creds-71c882d7c34cc120.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/webapp/webapp/gha-creds-71c882d7c34cc120.json
    CLOUDSDK_CORE_PROJECT: $project_id
    CLOUDSDK_PROJECT: $project_id
    GCLOUD_PROJECT: $project_id
    GCP_PROJECT:$project_id
    GOOGLE_CLOUD_PROJECT: $project_id
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 2.1.0
Retrieving application default credentials...
Retrieving credentials from gcloud...
Error: Fail to get credentials. Please run: 
`gcloud auth application-default login`, `gcloud auth login`, or 
`export GOOGLE_APPLICATION_CREDENTIALS=<path/to/service/account/key>`
    at Object.getCreds (/opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/google-artifactregistry-auth/src/auth.js:40:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/google-artifactregistry-auth/src/main.js:83:19)
```
`--verbose` flag yields some more insight:
```
Retrieving application default credentials...
Failed to retrieve application default credentials: Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).. Fall back to gcloud credentials.
Retrieving credentials from gcloud...
Failed to retrieve credentials from gcloud: Command failed: gcloud auth print-access-token
ERROR: (gcloud.auth.print-access-token) There was a problem refreshing your current auth tokens: ('Unable to acquire impersonated credentials', '{\n  "error": {\n    "code": 403,\n    "message": "Permission \'iam.serviceAccounts.getAccessToken\' denied on resource (or it may not exist).",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.ErrorInfo",\n        "reason": "IAM_PERMISSION_DENIED",\n        "domain": "iam.googleapis.com",\n        "metadata": {\n          "permission": "iam.serviceAccounts.getAccessToken"\n        }\n      }\n    ]\n  }\n}\n')
```

But I have verified these permissions do in fact work on the role, and as an extra step based on closed issues here.
```
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
        
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: 'hunch'
      run: gcloud auth login --cred-file=${{ steps.auth.outputs.credentials_file_path }}
```
Succeeds.

Looking at the SA
```
gcloud iam service-accounts get-iam-policy github@$project_id.iam.gserviceaccount.com
bindings:
- members:
  - serviceAccount:github@$project_id.iam.gserviceaccount.com
  role: roles/iam.serviceAccountTokenCreator
- members:
  - principalSet://iam.googleapis.com/projects/$project_number/locations/global/workloadIdentityPools/github-actions/attribute.repository_owner/$repo_owner
  - principalSet://iam.googleapis.com/projects/$project_number/locations/global/workloadIdentityPools/githubactions/attribute.repository/$repo_owner/$repo
  role: roles/iam.workloadIdentityUser
etag: BwYZjK4LQX0=
version: 1
```

Any insights would be appreciated.  Can provide more info as needed.
